# Generated by Django 5.1.1 on 2024-09-30 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_id_alter_order_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='total',
        ),
    ]
