apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-backend-svc
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
    app: {{ include "..fullname" . }}-backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-frontend-svc
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
    app: {{ include "..fullname" . }}-frontend
