name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend]
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Get short SHA
        id: short-sha
        uses: hudsonm62/short-sha@v1

      - name: Check if service has changed
        id: check_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep "^${{ matrix.service }}/"; then
            echo "SERVICE_CHANGED=true" >> $GITHUB_ENV
          else
            echo "SERVICE_CHANGED=false" >> $GITHUB_ENV
          fi

      - run: echo ${{ steps.check_changes.outputs.SERVICE_CHANGED }}

      - name: Build Docker image
        if: steps.check_changes.outputs.SERVICE_CHANGED == 'true'
        working-directory: ${{ matrix.service }}
        run: |
          docker build -t '$DOCKER_USERNAME/m-commerce-${{ matrix.service }}:${{ steps.short-sha.outputs.sha }}' .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '$DOCKER_USERNAME/m-commerce-${{ matrix.service }}:${{ steps.short-sha.outputs.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
  
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

      - name: Push Docker image
        if: steps.check_changes.outputs.SERVICE_CHANGED == 'true'
        run: docker push $DOCKER_USERNAME/m-commerce-${{ matrix.service }}:${{ steps.short-sha.outputs.sha }}
