name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend]
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Get short SHA
        id: short-sha
        uses: hudsonm62/short-sha@v1

      - name: Check for changes in directory
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: '${{ matrix.service }}/**'
          files_ignore: '${{ matrix.service }}/*.md'

      - run: echo ${{ steps.changed-files.outputs.any_modified }}

      - name: Build Docker image
        if: steps.changed-files.outputs.any_modified == 'true'
        working-directory: ${{ matrix.service }}
        run: |
          docker build -t $DOCKER_USERNAME/m-commerce-${{ matrix.service }}:${{ steps.short-sha.outputs.sha }} .

      - name: Run Trivy vulnerability scanner
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/m-commerce-${{ matrix.service }}:${{ steps.short-sha.outputs.sha }}'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        
      - name: Login to Docker Hub
        if: steps.changed-files.outputs.any_modified == 'true'
        uses: docker/login-action@v3
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

      - name: Push Docker image
        if: steps.changed-files.outputs.any_modified == 'true'
        run: docker push $DOCKER_USERNAME/m-commerce-${{ matrix.service }}:${{ steps.short-sha.outputs.sha }}
